#**Objective**

To develop an interactive dashboard that integrates customer, geographic, and purchase data to identify who high-value customers are, where they are located, and what they buy—enabling actionable insights and continuous, data-driven decision-making.

# **1. Import Library**

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime

# **2. Data Loading and Preprocessing**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_customers = pd.read_csv('/content/drive/MyDrive/Xom Analytics class/Buoi 6 Cohort analysis/Buoi 6 HW/Customer (1).csv')
df_ecomsales = pd.read_csv('/content/drive/MyDrive/Xom Analytics class/Buoi 6 Cohort analysis/Buoi 6 HW/EcomSales (2).csv')
df_products = pd.read_csv('/content/drive/MyDrive/Xom Analytics class/Buoi 6 Cohort analysis/Buoi 6 HW/Product (3).csv')
df_region = pd.read_csv('/content/drive/MyDrive/Xom Analytics class/Buoi 6 Cohort analysis/Buoi 6 HW/Region (1).csv')

In [ ]:
df_ecomsales

,RowID,OrderID,OrderDate,CustomerID,Segment,RegionCode,ProductCode,Quantity,Sales,Discount,Profit
0,25221,IN-2012-TH211151-41003,4/4/2020,TH-211151,Corporate,RRR0001,P000001,13,416,0.0,208.0
1,29464,ID-2013-BD116051-41518,9/1/2021,BD-116051,Consumer,R0002,PPP000002,4,20,0.0,10.0
2,27311,IN-2015-TS212051-42173,6/18/2023,TS-212051,Corporate,R0003,P000003,2,20,0.0,8.0
3,28882,IN-2014-SU206651-41899,9/17/2022,SU-206651,Self-Employed,R0003,P000004,4,556,0.0,55.6
4,27992,IN-2015-GM144551-42217,8/1/2023,GM-144551,Self-Employed,R0003,P000005,2,6,0.0,0.6
...,...,...,...,...,...,...,...,...,...,...,...
51285,42718,ZA-2015-GR4560147-42216,7/31/2023,GR-4560147,Corporate,R3825,P006655,14,812,0.7,-243.6
51286,43446,ZA-2015-BT1395147-42336,11/28/2023,BT-1395147,Corporate,R3823,P010293,7,21,0.7,-6.3
51287,42929,ZA-2013-DN3690147-41429,6/4/2021,DN-3690147,Consumer,R3823,P008070,1,9,0.7,-1.8
51288,42930,ZA-2013-DN3690147-41429,6/4/2021,DN-3690147,Consumer,R3823,P011064,1,26,0.7,-5.2
51289,49480,ZA-2015-BT1305147-42338,11/30/2023,BT-1305147,Self-Employed,R3822,P000716,2,70,0.7,-21.0

In [ ]:
df_ecomsales['Revenue'] = df_ecomsales['Sales'] - (df_ecomsales['Discount'] * df_ecomsales['Sales'])
display(df_ecomsales.head(20))

,RowID,OrderID,OrderDate,CustomerID,Segment,RegionCode,ProductCode,Quantity,Sales,Discount,Profit,Revenue
0,25221,IN-2012-TH211151-41003,4/4/2020,TH-211151,Corporate,RRR0001,P000001,13,416,0.0,208.0,416.0
1,29464,ID-2013-BD116051-41518,9/1/2021,BD-116051,Consumer,R0002,PPP000002,4,20,0.0,10.0,20.0
2,27311,IN-2015-TS212051-42173,6/18/2023,TS-212051,Corporate,R0003,P000003,2,20,0.0,8.0,20.0
3,28882,IN-2014-SU206651-41899,9/17/2022,SU-206651,Self-Employed,R0003,P000004,4,556,0.0,55.6,556.0
4,27992,IN-2015-GM144551-42217,8/1/2023,GM-144551,Self-Employed,R0003,P000005,2,6,0.0,0.6,6.0
5,24598,IN-2015-CA120551-42085,3/22/2023,CA-120551,Self-Employed,R0002,P000006,3,18,0.0,7.2,18.0
6,29465,ID-2013-BD116051-41518,9/1/2021,BD-116051,Consumer,R0002,P000007,9,369,0.0,36.9,369.0
7,29095,IN-2013-BG110351-41545,9/28/2021,BG-110351,Consumer,R0003,P000008,2,22,0.0,2.2,22.0
8,25231,ID-2013-SS201401-41624,12/16/2021,SS-201401,Corporate,R0003,P000009,1,10,0.0,1.0,10.0
9,25220,IN-2012-TH211151-41003,4/4/2020,TH-211151,Corporate,RRR0001,PPP000010,5,70,0.0,35.0,70.0
10,29097,IN-2013-BG110351-41545,9/28/2021,BG-110351,Consumer,R0003,P000011,4,44,0.0,22.0,44.0
11,27310,IN-2015-TS212051-42173,6/18/2023,TS-212051,Corporate,R0003,P000012,12,408,0.0,163.2,408.0
12,25218,IN-2012-TH211151-41003,4/4/2020,TH-211151,Corporate,R0001,P000013,18,216,0.0,108.0,216.0
13,29586,IN-2013-DW131951-41430,6/5/2021,DW-131951,Corporate,R0003,P000014,9,126,0.0,63.0,126.0
14,29584,IN-2013-DW131951-41430,6/5/2021,DW-131951,Corporate,R0003,P000015,20,220,0.0,110.0,220.0
15,29583,IN-2013-DW131951-41430,6/5/2021,DW-131951,Corporate,R0003,P000016,18,180,0.0,90.0,180.0
16,24294,IN-2014-JM156551-41905,9/23/2022,JM-156551,Corporate,R0003,P000017,15,735,0.0,367.5,735.0
17,29494,IN-2014-LO171701-41906,9/24/2022,LO-171701,Corporate,R0003,P000018,12,336,0.0,168.0,336.0
18,28265,IN-2014-AH105851-41970,11/27/2022,AH-105851,Consumer,R0003,P000019,6,36,0.0,18.0,36.0
19,28967,IN-2015-VB217451-42349,12/11/2023,VB-217451,Corporate,R0003,P000020,4,32,0.0,12.8,32.0

# **3. Table Merging**

In [ ]:
df= df_ecomsales.merge(df_customers, on='CustomerID', how= 'inner')
df.head(10)

,RowID,OrderID,OrderDate,CustomerID,Segment,RegionCode,ProductCode,Quantity,Sales,Discount,...,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,EducationLevel,Occupation,HomeOwner
0,25221,IN-2012-TH211151-41003,4/4/2020,TH-211151,Corporate,RRR0001,P000001,13,416,0.0,...,Jon,Huang,6/18/1962,M,M,jon24@hotmail.com,90000,Bachelors,Professional,Y
1,29464,ID-2013-BD116051-41518,9/1/2021,BD-116051,Consumer,R0002,PPP000002,4,20,0.0,...,Eugene,Torres,6/16/1985,S,M,eugene10@hotmail.com,60000,Bachelors,Professional,N
2,27311,IN-2015-TS212051-42173,6/18/2023,TS-212051,Corporate,R0003,P000003,2,20,0.0,...,Ruben,Zhu,6/28/1985,M,M,ruben35@hotmail.com,60000,Bachelors,Professional,Y
3,28882,IN-2014-SU206651-41899,9/17/2022,SU-206651,Self-Employed,R0003,P000004,4,556,0.0,...,Christy,Johnson,8/4/1988,S,F,christy12@hotmail.com,70000,Bachelors,Professional,N
4,27992,IN-2015-GM144551-42217,8/1/2023,GM-144551,Self-Employed,R0003,P000005,2,6,0.0,...,Elizabeth,Ruiz,1/12/1960,S,F,elizabeth5@hotmail.com,80000,Bachelors,Professional,Y
5,24598,IN-2015-CA120551-42085,3/22/2023,CA-120551,Self-Employed,R0002,P000006,3,18,0.0,...,Julio,Mehta,7/9/1970,S,M,julio1@hotmail.com,70000,Bachelors,Professional,Y
6,29465,ID-2013-BD116051-41518,9/1/2021,BD-116051,Consumer,R0002,P000007,9,369,0.0,...,Eugene,Torres,6/16/1985,S,M,eugene10@hotmail.com,60000,Bachelors,Professional,N
7,29095,IN-2013-BG110351-41545,9/28/2021,BG-110351,Consumer,R0003,P000008,2,22,0.0,...,Marco,Verhoff,4/24/1975,M,M,marco14@hotmail.com,60000,Bachelors,Professional,Y
8,25231,ID-2013-SS201401-41624,12/16/2021,SS-201401,Corporate,R0003,P000009,1,10,0.0,...,Robin,Carlson,5/22/1971,S,F,rob4@hotmail.com,60000,Bachelors,Professional,Y
9,25220,IN-2012-TH211151-41003,4/4/2020,TH-211151,Corporate,RRR0001,PPP000010,5,70,0.0,...,Jon,Huang,6/18/1962,M,M,jon24@hotmail.com,90000,Bachelors,Professional,Y

# **4. RFM Analysis**

In [ ]:
df_rfm_groupby = df_ecomsales.groupby(by = 'CustomerID',as_index=False).agg(max_date = ('OrderDate','max')
                                                                     ,frequency = ('OrderID','nunique')
                                                                     ,monetary = ('Revenue','sum'))

In [ ]:
df_rfm_groupby['recency'] = (datetime.now() - pd.to_datetime(df_rfm_groupby['max_date'])).dt.days

In [ ]:
df_rfm_groupby

         CustomerID    max_date  frequency  monetary  recency
0       AA-10315102    7/3/2020          2   506.800     2113
1       AA-10315120   5/16/2021          1    63.000     1796
2       AA-10315139   9/19/2022          4   596.600     1305
3      AA-103151402   6/30/2023          2   195.800     1021
4      AA-103151404   3/30/2020          2   213.600     2208
...             ...         ...        ...       ...      ...
17410    ZD-2192548   8/17/2021          3   164.200     1703
17411    ZD-2192564   2/21/2020          1   152.000     2246
17412     ZD-219257   9/19/2020          1   111.600     2035
17413    ZD-2192582   6/18/2023          2   126.354     1033
17414    ZD-2192596  12/12/2021          1   112.000     1586

[17415 rows x 5 columns]

In [ ]:
df_rfm_groupby['R_score'] = pd.qcut(df_rfm_groupby['recency'], q = 5, duplicates='drop')
df_rfm_groupby['F_score'] = pd.qcut(df_rfm_groupby['frequency'], q = 5, duplicates='drop')
df_rfm_groupby['M_score'] = pd.qcut(df_rfm_groupby['monetary'], q = 5, duplicates='drop')

df_rfm_groupby

,CustomerID,max_date,frequency,monetary,recency,R_score,M_score,F_score
0,AA-10315102,7/3/2020,2,506.800,2113,"(1843.0, 2297.0]","(459.04, 6840.0]","(0.999, 2.0]"
1,AA-10315120,5/16/2021,1,63.000,1796,"(1523.0, 1843.0]","(38.0, 96.0]","(0.999, 2.0]"
2,AA-10315139,9/19/2022,4,596.600,1305,"(1272.6, 1523.0]","(459.04, 6840.0]","(2.0, 9.0]"
3,AA-103151402,6/30/2023,2,195.800,1021,"(1002.0, 1272.6]","(96.0, 203.0]","(0.999, 2.0]"
4,AA-103151404,3/30/2020,2,213.600,2208,"(1843.0, 2297.0]","(203.0, 459.04]","(0.999, 2.0]"
...,...,...,...,...,...,...,...,...
17410,ZD-2192548,8/17/2021,3,164.200,1703,"(1523.0, 1843.0]","(96.0, 203.0]","(2.0, 9.0]"
17411,ZD-2192564,2/21/2020,1,152.000,2246,"(1843.0, 2297.0]","(96.0, 203.0]","(0.999, 2.0]"
17412,ZD-219257,9/19/2020,1,111.600,2035,"(1843.0, 2297.0]","(96.0, 203.0]","(0.999, 2.0]"
17413,ZD-2192582,6/18/2023,2,126.354,1033,"(1002.0, 1272.6]","(96.0, 203.0]","(0.999, 2.0]"
17414,ZD-2192596,12/12/2021,1,112.000,1586,"(1523.0, 1843.0]","(96.0, 203.0]","(0.999, 2.0]"

In [ ]:
df_rfm_groupby['F_score'].unique()

[(0.999, 2.0], (2.0, 9.0]]
Categories (2, interval[float64, right]): [(0.999, 2.0] < (2.0, 9.0]]

In [ ]:
df_rfm_groupby['R_score'] = pd.qcut(df_rfm_groupby['recency'], q=5, labels=[5, 4, 3, 2, 1], duplicates='drop')
df_rfm_groupby['M_score'] = pd.qcut(df_rfm_groupby['monetary'], q=5, labels=[1, 2, 3, 4, 5], duplicates='drop')
df_rfm_groupby

,CustomerID,max_date,frequency,monetary,recency,R_score,M_score,F_score_x,F_score_y,F_score
0,AA-10315102,7/3/2020,2,506.800,2113,1,5,"(0.999, 2.0]",1,1
1,AA-10315120,5/16/2021,1,63.000,1796,2,2,"(0.999, 2.0]",1,1
2,AA-10315139,9/19/2022,4,596.600,1305,3,5,"(2.0, 9.0]",2,2
3,AA-103151402,6/30/2023,2,195.800,1021,4,3,"(0.999, 2.0]",1,1
4,AA-103151404,3/30/2020,2,213.600,2208,1,4,"(0.999, 2.0]",1,1
...,...,...,...,...,...,...,...,...,...,...
17410,ZD-2192548,8/17/2021,3,164.200,1703,2,3,"(2.0, 9.0]",2,2
17411,ZD-2192564,2/21/2020,1,152.000,2246,1,3,"(0.999, 2.0]",1,1
17412,ZD-219257,9/19/2020,1,111.600,2035,1,3,"(0.999, 2.0]",1,1
17413,ZD-2192582,6/18/2023,2,126.354,1033,4,3,"(0.999, 2.0]",1,1
17414,ZD-2192596,12/12/2021,1,112.000,1586,2,3,"(0.999, 2.0]",1,1

In [ ]:
df_rfm_groupby = df_rfm_groupby.drop(columns=['F_Score', 'F_score_x', 'F_score_y'], errors='ignore')

In [ ]:
df_freq = df_rfm_groupby['frequency'].unique()
df_freq = pd.DataFrame(df_freq, columns=['frequency'])

df_freq['F_score'] = pd.qcut(df_freq['frequency'], q=5, labels=[1, 2, 3, 4, 5])
df_freq

   frequency F_score
0          2       1
1          1       1
2          4       2
3          3       2
4          5       3
5          6       4
6          7       4
7          9       5
8          8       5

In [ ]:
df_rfm_groupby = df_rfm_groupby.merge(
    df_freq[['frequency', 'F_score']],
    on='frequency',
    how='left'
)
df_rfm_groupby.head()

,CustomerID,max_date,frequency,monetary,recency,R_score,M_score,F_score
0,AA-10315102,7/3/2020,2,506.8,2113,1,5,1
1,AA-10315120,5/16/2021,1,63.0,1796,2,2,1
2,AA-10315139,9/19/2022,4,596.6,1305,3,5,2
3,AA-103151402,6/30/2023,2,195.8,1021,4,3,1
4,AA-103151404,3/30/2020,2,213.6,2208,1,4,1

In [ ]:
df_rfm_groupby.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17415 entries, 0 to 17414
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  17415 non-null  object
 1   max_date    17415 non-null  object
 2   frequency   17415 non-null  int64
 3   monetary    17415 non-null  float64
 4   recency     17415 non-null  int64
 5   R_score     17415 non-null  category
 6   M_score     17415 non-null  category
 7   F_score     17415 non-null  category
dtypes: category(3), float64(1), int64(2), object(2)
memory usage: 732.0+ KB

In [ ]:
df_rfm_groupby['R_score'] = df_rfm_groupby['R_score'].astype(int)
df_rfm_groupby['F_score'] = df_rfm_groupby['F_score'].astype(int)
df_rfm_groupby['M_score'] = df_rfm_groupby['M_score'].astype(int)
df_rfm_groupby.head()

,CustomerID,max_date,frequency,monetary,recency,R_score,M_score,F_score
0,AA-10315102,7/3/2020,2,506.8,2113,1,5,1
1,AA-10315120,5/16/2021,1,63.0,1796,2,2,1
2,AA-10315139,9/19/2022,4,596.6,1305,3,5,2
3,AA-103151402,6/30/2023,2,195.8,1021,4,3,1
4,AA-103151404,3/30/2020,2,213.6,2208,1,4,1

In [ ]:
df_rfm_groupby['F_score'].unique()

array([1, 2, 3, 4, 5])

In [ ]:
df_rfm_groupby['RFM_score'] = df_rfm_groupby['R_score'] * 100 + df_rfm_groupby['F_score'] * 10 + df_rfm_groupby['M_score']
df_rfm_groupby

,CustomerID,max_date,frequency,monetary,recency,R_score,M_score,F_score,RFM_score
0,AA-10315102,7/3/2020,2,506.800,2113,1,5,1,115
1,AA-10315120,5/16/2021,1,63.000,1796,2,2,1,212
2,AA-10315139,9/19/2022,4,596.600,1305,3,5,2,325
3,AA-103151402,6/30/2023,2,195.800,1021,4,3,1,413
4,AA-103151404,3/30/2020,2,213.600,2208,1,4,1,114
...,...,...,...,...,...,...,...,...,...
17410,ZD-2192548,8/17/2021,3,164.200,1703,2,3,2,223
17411,ZD-2192564,2/21/2020,1,152.000,2246,1,3,1,113
17412,ZD-219257,9/19/2020,1,111.600,2035,1,3,1,113
17413,ZD-2192582,6/18/2023,2,126.354,1033,4,3,1,413
17414,ZD-2192596,12/12/2021,1,112.000,1586,2,3,1,213

#  **5. Customer Segmentation**

In [ ]:
df_rfm_groupby['RFM_Segment'] = 'Other'

# Champions
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([555, 554, 544, 545, 454, 455, 445]), 'RFM_Segment'] = 'Champions'

# Loyal
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([543, 444, 435, 355, 354, 345, 344, 335]), 'RFM_Segment'] = 'Loyal'

# Potential Loyalist
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([553, 551, 552, 541, 542, 533, 532, 531, 452, 451
                                                 , 442, 441, 431, 453, 433, 432, 423, 353, 352
                                                 , 351, 342, 341, 333, 323]), 'RFM_Segment'] = 'Potential Loyalist'

# Promising
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([525, 524, 523, 522, 521, 515, 514, 513
                                                 , 425, 424, 413, 414, 415, 315, 314, 313]), 'RFM_Segment'] = 'Promising'

# New Customers
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([512, 511, 422, 421, 412, 411, 311]), 'RFM_Segment'] = 'New Customers'

# Need Attention
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([535, 534, 443, 434, 343, 334, 325, 324]), 'RFM_Segment'] = 'Need Attention'

# About To Sleep
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([331, 321, 312, 221, 213, 231, 241, 251]), 'RFM_Segment'] = 'About To Sleep'

# At Risk
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([255, 254, 245, 244, 253, 252, 243, 242, 235
                                                 , 234, 225, 224, 153, 152, 145, 143, 142
                                                 , 135, 134, 133, 125, 124]), 'RFM_Segment'] = 'At Risk'

# Cannot Lose Them
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([155, 154, 144, 214, 215, 115, 114, 113]), 'RFM_Segment'] = 'Cannot Lose Them'

# Hibernating customers
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([332, 322, 233, 232, 223, 222, 132, 123, 122, 212, 211]), 'RFM_Segment'] = 'Hibernating customers'

# Lost customers
df_rfm_groupby.loc[df_rfm_groupby['RFM_score'].isin([111, 112, 121, 131, 141, 151]), 'RFM_Segment'] = 'Lost customers'

df_rfm_groupby

,CustomerID,max_date,frequency,monetary,recency,R_score,M_score,F_score,RFM_score,RFM_Segment
0,AA-10315102,7/3/2020,2,506.800,2113,1,5,1,115,Cannot Lose Them
1,AA-10315120,5/16/2021,1,63.000,1796,2,2,1,212,Hibernating customers
2,AA-10315139,9/19/2022,4,596.600,1305,3,5,2,325,Need Attention
3,AA-103151402,6/30/2023,2,195.800,1021,4,3,1,413,Promising
4,AA-103151404,3/30/2020,2,213.600,2208,1,4,1,114,Cannot Lose Them
...,...,...,...,...,...,...,...,...,...,...
17410,ZD-2192548,8/17/2021,3,164.200,1703,2,3,2,223,Hibernating customers
17411,ZD-2192564,2/21/2020,1,152.000,2246,1,3,1,113,Cannot Lose Them
17412,ZD-219257,9/19/2020,1,111.600,2035,1,3,1,113,Cannot Lose Them
17413,ZD-2192582,6/18/2023,2,126.354,1033,4,3,1,413,Promising
17414,ZD-2192596,12/12/2021,1,112.000,1586,2,3,1,213,About To Sleep

In [ ]:
treemap_input = df_rfm_groupby.groupby(by = 'RFM_Segment',as_index=False).agg(count_cus = ('CustomerID','nunique')
                                                                            ,total_rev = ('monetary','sum'))
treemap_input

              RFM_Segment  count_cus    total_rev
0          About To Sleep       1285   136707.560
1                 At Risk        651   591595.136
2        Cannot Lose Them       2747  1379843.820
3               Champions         14    19791.460
4   Hibernating customers       1497    75106.312
5          Lost customers       1413    60026.484
6                   Loyal         61    98460.346
7          Need Attention        432   386234.822
8           New Customers       3538   134325.044
9      Potential Loyalist        103    15487.976
10              Promising       5674  2667504.140

# **6. Visualization**

In [ ]:
# Create a Treemap for customer count
fig = px.treemap(treemap_input, path=['RFM_Segment'], values='count_cus', title='RFM Segments - Customer Count Treemap')

# Show the plot
fig.show()

# Create a Treemap for total revenue
fig_rev = px.treemap(treemap_input, path=['RFM_Segment'], values='total_rev', title='RFM Segments - Total Revenue Treemap')

# Show the revenue plot
fig_rev.show()

In [92]:
df.to_csv('Customer_data.csv', index=False)
df_rfm_groupby.to_csv('rfm_segments.csv', index=False)

In [93]:
import os
os.listdir('/content')

['.config',
 'rfm_segments.csv',
 'drive',
 'Customer_data.csv',
 'full_dashboard_data.csv',
 'sample_data']

In [94]:
from google.colab import files
files.download('Customer_data.csv')
files.download('rfm_segments.csv')

In [ ]:
df_full['Revenue'].dtype        # phải là float64
df_full['Revenue'].head()

0    416.0
1     20.0
2     20.0
3    556.0
4      6.0
Name: Revenue, dtype: float64